pipeline:
  name: ecs
  identifier: ecs
  projectIdentifier: ECS
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Staging
        identifier: Staging
        description: ""
        type: Deployment
        spec:
          deploymentType: ECS
          service:
            serviceRef: httpd
          environment:
            environmentRef: Development
            deployToAll: false
            infrastructureDefinitions:
              - identifier: mansongecs
          execution:
            steps:
              - step:
                  name: ECS Rolling Deploy
                  identifier: ecsRollingDeploy
                  type: EcsRollingDeploy
                  timeout: 10m
                  spec: {}
                  sameAsAlreadyRunningInstances: true
                  forceNewDeployment: true
            rollbackSteps:
              - step:
                  name: ECS Rolling Rollback
                  identifier: ecsRollingRollback
                  type: EcsRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
